# The global Makefile of the jupiter project
#
# Copyright 2008 John Calcote <http://freesoftwaremagazine.com/authors/John%20Calcote>
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: WTFPL
all clean jupiter:
	$(MAKE) -C src $@
